In [1]:
def rockpaperscissors():
    def visual():
        import time
        import cv2
        from keras.models import load_model
        import numpy as np
        model = load_model('/Users/nickc/Desktop/converted_keras/rps.h5')
        cap = cv2.VideoCapture(0)
        data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
        choice_list = ["nothing", "rock", "paper", "scissors"]
        choice_number = []
        start = time.time()
        end = time.time()
        final = start - end
        while final < 5.0: 
            ret, frame = cap.read()
            resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
            image_np = np.array(resized_frame)
            normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
            data[0] = normalized_image
            prediction = model.predict(data)
            cv2.imshow('frame', frame)
            # Press q to close the window
            if prediction[0][0] == max(prediction[0]):
               choice_number.append(0)
            elif prediction[0][1] == max(prediction[0]):
                choice_number.append(1)
            elif prediction[0][2] == max(prediction[0]):
                choice_number.append(2)
            elif prediction[0][3] == max(prediction[0]):
                choice_number.append(3)
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break
        print()
        # After the loop release the cap object
        cap.release()
        # Destroy all the windows
        cv2.destroyAllWindows()
        
    def player1_choose():
        string_check = True
        choice_check = True
        while string_check is True:
            try:
                while choice_check is True:
                    print("Player 1 choose Rock, Paper or Scissors: ")
                    choice = visual()
                    string_check = False
                    if choice == "rock" or choice == "paper" or choice == "scissiors":
                        choice_check = False
                    else:
                        print("This input is invalid. Please choose Rock, Paper or Scissors.")
            except Exception:
                print("This choice is invalid. Please try again.")
            
        player1 = None

        if choice == "rock":
            player1 = choice
        elif choice == "paper":
            player1 = choice
        elif choice == "scissors":
            player1 = choice

        return (player1).title()

    def player2_choose():
        string_check = True
        choice_check = True
        while string_check is True:
            try:
                while choice_check is True:
                    choice = input("Player 2 choose Rock, Paper or Scissors: ").lower()
                    string_check = False
                    if choice == "rock" or choice == "paper" or choice == "scissors":
                        choice_check = False
                    else:
                        print("This input is invalid. Please choose Rock, Paper or Scissors.")
            except Exception:
                print("This choice is invalid. Please try again.")
        
        player2 = None

        if choice == "rock":
            player2 = choice
            
        elif choice == "paper":
            player2 = choice
            
        elif choice == "scissors":
            player2 = choice
            
        return (player2).title()

    def outcome(choice1, choice2):
        if choice1 == "Rock" and choice2 == "Scissors":
            print("Player 1 wins this round!")
            return 1
        elif choice1 == "Paper" and choice2 == "Scissors":
            print("Player 2 wins this round!")
            return 2
        elif choice1 == "Scissors" and choice2 == "Rock":
            print("Player 2 wins this round!")
            return 2
        elif choice1 == "Paper" and choice2 == "Rock":
            print("Player 1 wins this round!")
            return 1
        elif choice1 == "Rock" and choice2 == "Paper":
            print("Player 2 wins this round!")
            return 2
        elif choice1 == "Scissors" and choice2 == "Paper":
            print("Player 1 wins this round!")
            return 1
        elif choice1 == choice2:
            print("It's a draw!")
            return 0
        
    def computer():
        computer_choices = ["Rock", "Paper", "Scissors"]
        return random.choice(computer_choices)

    import random

    game_on = True
    round_counter = 0
    while game_on is True:
        print("Welcome to the Rock, Paper, Scissors game!")
        checks = True
        game_type_check = True
        round_check = True
        while checks is True:
            try:
                while game_type_check is True:
                    game_type = int(input("Do you want to play Singleplayer or Multiplayer mode? (Input 1 for Singleplayer , 2 for Multiplayer)"))
                    if game_type == 1 or game_type == 2:
                        game_type_check = False
                        while round_check is True:
                            number_of_rounds = int(input("How many rounds do you want to play this game? "))
                            if number_of_rounds % 2 == 0:
                                print("Sorry this is an invaid input. Please input an odd integer number.")
                            else:
                                round_check = False
                                checks = False
                    else:
                        print("This input is invaild> Please choose either 1 or 2.")
            except Exception:
                print("Sorry this is an invaid input. Please input an integer number.")
        

        player1_score = 0

        player2_score = 0

        
        round_on = True
        while round_on is True:
            if game_type == 1:
                opponent = computer()
            else:
                opponent = player2_choose()

            player1_choice = player1_choose()
            print(f"Player 1 chooses: {player1_choice}")

            print(f"Player 2 chooses: {opponent}")

            winner = outcome(player1_choice, opponent)
            
            if winner == 1:
                player1_score += 1
                round_counter += 1
            elif winner == 2:
                player2_score += 1
                round_counter += 1

            print(f"The score is {player1_score} : {player2_score}")
            
            print(round_counter, number_of_rounds)
            
            if round_counter == number_of_rounds and player1_score != player2_score:
                print(f"Game over! The final score is {player1_score} : {player2_score}.")
                if player1_score > player2_score:
                    print("Player 1 won the game!")
                else:
                    print("Player 2 won the game!")
                play_again_type_check = True
                play_again_check = True
                while play_again_check is True:
                    try:
                        play_again = (input("Do you want to play again? (Yes/No)")).lower()
                        if play_again == "yes" or play_again == "no":
                            play_again_check = False
                            round_on = False
                        else:
                            print("That is an invaild input. Please choose Yes or No.")
                    except Exception:
                        print("That is an invaild input. Please choose the string Yes or No.")
                if play_again == "no":
                    game_on = False
                    round_on = False
                    print("Thank you for playing Roack, Paper, Scissors.")

rockpaperscissors()


Welcome to the Rock, Paper, Scissors game!
Player 1 choose Rock, Paper or Scissors: 
nothing
[[0.8772739  0.00198198 0.1018063  0.01893782]]
scissors
[[0.00900252 0.00245526 0.01460585 0.97393644]]
scissors
[[0.04068552 0.0042548  0.04308122 0.9119784 ]]
scissors
[[0.0683683  0.0135108  0.10425589 0.81386507]]
scissors
[[0.09764186 0.01097402 0.09989464 0.79148954]]
scissors
[[0.06350819 0.00635236 0.06451623 0.8656232 ]]
scissors
[[1.0040279e-02 7.1423780e-04 8.5250763e-03 9.8072046e-01]]
scissors
[[0.01534374 0.00305182 0.01932136 0.962283  ]]
scissors
[[7.0541571e-03 1.4442725e-04 4.8026997e-03 9.8799872e-01]]
scissors
[[0.04798624 0.00400443 0.02657249 0.92143685]]
scissors
[[0.04553087 0.00196077 0.04759382 0.9049146 ]]
scissors
[[3.7345894e-02 8.5028552e-04 2.1922743e-02 9.3988109e-01]]
scissors
[[1.8904731e-02 7.9773582e-04 1.3463096e-02 9.6683449e-01]]
scissors
[[5.0386372e-03 3.4392040e-04 6.6266353e-03 9.8799080e-01]]
scissors
[[0.14308865 0.00491107 0.0706444  0.7813558 ]]
s

In [12]:
import statistics
small = [5, 5, 5, 4, 4, 4]
car = statistics.mode(small)
print(car)


5
